{
  "uid" : "ac5444ffd55ff492",
  "name" : "test_information",
  "fullName" : "test_case.test_information3#test_information",
  "historyId" : "ac7f4079c168e0d169d5df8db56ab99f",
  "time" : {
    "start" : 1618483264559,
    "stop" : 1618483264563,
    "duration" : 4
  },
  "description" : "信息流接口",
  "descriptionHtml" : "<p>信息流接口</p>\n",
  "status" : "broken",
  "statusMessage" : "yaml.parser.ParserError: while parsing a flow mapping\n  in \"./yaml_data/yaml_request_data.yaml\", line 44, column 15\nexpected ',' or '}', but got '<scalar>'\n  in \"./yaml_data/yaml_request_data.yaml\", line 47, column 9",
  "statusTrace" : "@allure.description(\"信息流接口\")\n    @allure.testcase('http://bug.com/user-login-Lw==.html', name='测试接口')\n    def test_information():\n        # 读取yaml内的数据\n>       yaml_data = load_yaml_data.load_data('./yaml_data/yaml_request_data.yaml')\n\ntest_case\\test_information3.py:12: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nconfigfile\\load_yaml_data.py:6: in load_data\n    data = yaml.load(file, Loader=yaml.FullLoader)\n..\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\yaml\\__init__.py:114: in load\n    return loader.get_single_data()\n..\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\yaml\\constructor.py:49: in get_single_data\n    node = self.get_single_node()\n..\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\yaml\\composer.py:36: in get_single_node\n    document = self.compose_document()\n..\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\yaml\\composer.py:55: in compose_document\n    node = self.compose_node(None, None)\n..\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\yaml\\composer.py:84: in compose_node\n    node = self.compose_mapping_node(anchor)\n..\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\yaml\\composer.py:133: in compose_mapping_node\n    item_value = self.compose_node(node, item_key)\n..\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\yaml\\composer.py:84: in compose_node\n    node = self.compose_mapping_node(anchor)\n..\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\yaml\\composer.py:133: in compose_mapping_node\n    item_value = self.compose_node(node, item_key)\n..\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\yaml\\composer.py:84: in compose_node\n    node = self.compose_mapping_node(anchor)\n..\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\yaml\\composer.py:127: in compose_mapping_node\n    while not self.check_event(MappingEndEvent):\n..\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\yaml\\parser.py:98: in check_event\n    self.current_event = self.state()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <yaml.loader.FullLoader object at 0x00000287231B6FA0>, first = False\n\n    def parse_flow_mapping_key(self, first=False):\n        if not self.check_token(FlowMappingEndToken):\n            if not first:\n                if self.check_token(FlowEntryToken):\n                    self.get_token()\n                else:\n                    token = self.peek_token()\n>                   raise ParserError(\"while parsing a flow mapping\", self.marks[-1],\n                            \"expected ',' or '}', but got %r\" % token.id, token.start_mark)\nE                   yaml.parser.ParserError: while parsing a flow mapping\nE                     in \"./yaml_data/yaml_request_data.yaml\", line 44, column 15\nE                   expected ',' or '}', but got '<scalar>'\nE                     in \"./yaml_data/yaml_request_data.yaml\", line 47, column 9\n\n..\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\yaml\\parser.py:549: ParserError",
  "flaky" : false,
  "beforeStages" : [ ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "parentSuite",
    "value" : "test_case"
  }, {
    "name" : "suite",
    "value" : "test_information3"
  }, {
    "name" : "host",
    "value" : "zhangfushuai"
  }, {
    "name" : "thread",
    "value" : "26992-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "test_case.test_information3"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ {
    "name" : "测试接口",
    "url" : "http://bug.com/user-login-Lw==.html",
    "type" : "test_case"
  } ],
  "hidden" : true,
  "retry" : true,
  "extra" : {
    "categories" : [ ],
    "tags" : [ ]
  },
  "source" : "ac5444ffd55ff492.json",
  "parameterValues" : [ ]
}